steps:
  - id: "Run test"
    name: gcr.io/cloud-builders/gcloud
    entrypoint: "bash"
    args: ["./test.sh"]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "asia-east1-docker.pkg.dev/test-cloud-build-379706/quickstart-docker-repo/quickstart-image:tag1",
        ".",
      ]
images:
  - "asia-east1-docker.pkg.dev/test-cloud-build-379706/quickstart-docker-repo/quickstart-image:tag1"
