steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "asia-east1-docker.pkg.dev/test-cloud-build-379706/quickstart-docker-repo/quickstart-image:tag1",
        ".",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "run",
        "asia-east1-docker.pkg.dev/test-cloud-build-379706/quickstart-docker-repo/quickstart-image:tag1",
        "python",
        "manage.py",
        "test",
      ]
images:
  - "asia-east1-docker.pkg.dev/test-cloud-build-379706/quickstart-docker-repo/quickstart-image:tag1"
